### ISSUE TITLE
Urgent: save and load the training result

### ISSUE THREAD

**Issue by delphiy** [joelmartinez/nBayes#13]
how to save and load the training result? 

C#

**Comment by joelmartinez** [comment]
Take a look at [`FileIndex`](https://github.com/joelmartinez/nBayes/blob/master/nBayes/FileIndex.cs) ... shows how to create an `Index` class that serializes the trained model onto disk. You can inherit from `Index` and save it wherever you need (db, etc.) :)

**Comment by joelmartinez** [comment]
You're using a memory index (which maintains the training data in memory only). As I mentioned above, look at either using a `FileIndex` (by replacing `Index.CreateMemoryIndex()` with `new FileIndex("filepath.xml")` and calling `.Open()` and `.Save()` before and after adding entries.

... or writing your own index that persists your data in whatever format you need :)
